### ISSUE TITLE
Master slave problem with sqlite

### ISSUE THREAD

**Issue by gimler** [instaclick/ICBaseTestBundle#25]
We have some problems with master slave doctrine configuration

``` yml
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        slaves:
            slave1:
                host:     %database_slave_1_host%
                port:     %database_slave_1_port%
                dbname:   %database_name%
                user:     %database_user%
                password: %database_password%
```

`FixturesLoader` line 190 and `SchemaLoader` line 109

```
        if ($parameters['master']) {
            $parameters = $parameters['master'];
        }
```

this use the master connection but now we get the following error

```
ErrorException: Warning: copy(/home/gfranke/.../app/cache/test/test.db): failed to open stream: No such file or directory in /home/gfranke/.../vendor/instaclick/base-test-bundle/IC/Bundle/Base/TestBundle/Test/Loader/SchemaLoader.php line 130

/home/gfranke/.../vendor/instaclick/base-test-bundle/IC/Bundle/Base/TestBundle/Test/Loader/SchemaLoader.php:130
/home/gfranke/.../vendor/instaclick/base-test-bundle/IC/Bundle/Base/TestBundle/Test/Loader/SchemaLoader.php:86
/home/gfranke/.../vendor/instaclick/base-test-bundle/IC/Bundle/Base/TestBundle/Test/Loader/FixtureLoader.php:211
/home/gfranke/.../vendor/instaclick/base-test-bundle/IC/Bundle/Base/TestBundle/Test/Loader/FixtureLoader.php:120
/home/gfranke/.../vendor/instaclick/base-test-bundle/IC/Bundle/Base/TestBundle/Test/Loader/FixtureLoader.php:80
/home/gfranke/.../vendor/instaclick/base-test-bundle/IC/Bundle/Base/TestBundle/Test/Functional/WebTestCase.php:60
```
